workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    openapi:
        inputs:
            - location: openapi.json
    openapi-developers:
        inputs:
            - location: openapi.json
    openapi-developers-final:
        inputs:
            - location: openapi.json
    openapi-developers-final-10:
        inputs:
            - location: openapi.json
    openapi-developers-final-11:
        inputs:
            - location: openapi.json
    openapi-developers-final-12:
        inputs:
            - location: openapi.json
    openapi-developers-final-13:
        inputs:
            - location: openapi.json
        registry:
            location: registry.speakeasyapi.dev/keymatelast/keymatelast/openapi-developers-final-13
targets:
    first-target:
        target: python
        source: openapi-developers-final-13
        publish:
            pypi:
                token: $pypi_token
