workflowVersion: 1.0.0
sources:
    openapi:
        inputs:
            - location: openapi.json
targets:
    first-target:
        target: python
        source: openapi
        publish:
            pypi:
                token: $pypi_token
